name: Generate ZIP, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release ZIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create directories
        run: |
          mkdir build 
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/wp-api-privacy.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/wp-api-privacy.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
